//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 趣车网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        public int CarId { get; set; }
        public string CarType { get; set; }
        public Nullable<int> CarFixyear { get; set; }
        public string CarDescribed { get; set; }
        public string CarColor { get; set; }
        public Nullable<decimal> CarSingleprice { get; set; }
        public Nullable<int> CarInventory { get; set; }
        public string CarImage { get; set; }
    }
}
